// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    BaseLoader: typeof import('./../components/BaseLoader.vue')['default']
    TheAside: typeof import('./../components/TheAside.vue')['default']
    TheHeader: typeof import('./../components/TheHeader.vue')['default']
    TheMain: typeof import('./../components/TheMain.vue')['default']
  }
}

export { }
